version: '3.2'

services:
  elasticsearch:
    image: elasticsearch:7.9.3
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      discovery.type: single-node
    networks:
      - elk_network
    deploy:
      mode: replicated
      replicas: 1

  logstash:
    image: logstash:7.9.3
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk_network
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:7.9.3
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk_network
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - elasticsearch

  cerebro:
    image: lmenezes/cerebro:0.9.2
    ports:
      - "9000:9000"
    networks:
      - elk_network
    deploy:
     mode: replicated
     replicas: 1

networks:
  elk_network:
    driver: bridge

volumes:
  elasticsearch: