version: '3.2'

services:
  es-data01:
    image: elasticsearch:7.9.3
    container_name: es-data01
    healthcheck:
      test: curl -f -u elastic:changeme http://localhost:9200/_cat/health || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 45s
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: es-data01
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      node.name: es-data01
      cluster.name: es-docker-cluster
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      discovery.seed_hosts: es-data02
      cluster.initial_master_nodes: es-data01
    networks:
      - elk_network
    deploy:
      mode: replicated
      replicas: 1

  es-data02:
    image: elasticsearch:7.9.3
    container_name: es-data02
    healthcheck:
      test: curl -f -u elastic:changeme http://localhost:9200/_cat/health || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 45s
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: es-data02
        target: /usr/share/elasticsearch/data
    environment:
      node.name: es-data02
      cluster.name: es-docker-cluster
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      discovery.seed_hosts: es-data01
      cluster.initial_master_nodes: es-data01
    networks:
      - elk_network
    deploy:
      mode: replicated
      replicas: 1

  logstash:
    image: logstash:7.9.3
    container_name: logstash
    healthcheck:
      test: curl -f -u elastic:changeme http://localhost:9600 || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 45s
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk_network
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - es-data01

  kibana:
    image: kibana:7.9.3
    container_name: kibana
    healthcheck:
      test: curl -f -u elastic:changeme http://localhost:5601 || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 45s
    environment:
      ELASTICSEARCH_HOSTS: http://es-data01:9200
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk_network
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - es-data01

  cerebro:
    image: lmenezes/cerebro:0.9.2
    container_name: cerebro
    ports:
      - "9000:9000"
    networks:
      - elk_network
    deploy:
     mode: replicated
     replicas: 1

networks:
  elk_network:
    driver: bridge

volumes:
  es-data01:
    driver: local
  es-data02:
    driver: local