server.name: kibana
server.host: 0.0.0.0
elasticsearch.hosts: [ "http://es-data01:9200" ]
monitoring.ui.container.elasticsearch.enabled: true

elasticsearch.username: elastic
elasticsearch.password: changeme